export const TABLE_RESIZE = 'TABLE_RESIZE';
export const TABLE_CHANGE_NUMBER = 'TABLE_CHANGE_NUMBER';
export const TABLE_CHANGE_FORMULA = 'TABLE_CHANGE_FORMULA';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CHANGE_STYLES = 'CHANGE_STYLES';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_ACCESS_TIME = 'CHANGE_ACCESS_TIME';
